pyms:
  services:
    metrics: true
    requests:
      data: ""
    swagger:
      path: ""
      file: "swagger.yaml"
  config:
    DEBUG: true
    TESTING: false
    APP_NAME: "Python Microservice"
    APPLICATION_ROOT: ""