CONFIGMAP_FILE_ENVIRONMENT = "CONFIGMAP_FILE"

DEFAULT_CONFIGMAP_FILENAME = "config.yml"

CRYPT_FILE_KEY_ENVIRONMENT = "KEY_FILE"

DEFAULT_KEY_FILENAME = "key.key"

LOGGER_NAME = "pyms"

CONFIG_BASE = "pyms.config"

SERVICE_BASE = "pyms.services"

PYMS_CONFIG_WHITELIST_KEYWORDS = ["config", "services"]
