pyms:
  requests:
    data: ""
  swagger:
    path: ""
    file: "swagger.yaml"
  tracer:
    client: "jaeger"
    host: "localhost"
    component_name: "Python Microservice"
my-ms:
  DEBUG: true
  TESTING: false
  APP_NAME: "Python Microservice"
  APPLICATION_ROOT: ""