pyms:
  services:
    requests:
      propagate_headers: true
    tracer:
      client: "jaeger"
      host: "localhost"
      component_name: "Python Microservice2"
  config:
    APP_NAME: "Python Microservice2"
    debug: true
